apiVersion: v1
kind: Pod
metadata:
  name: webs
  labels:
    appType: html

spec:
  containers:
    - name: httpd
      image: nginx
      ports:
       - name: ports
         containerPort: 80
         protocol: TCP
